# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes to /etc/nixos/configuration.nix instead.
{ pkgs, config, lib, modulesPath, ... }:
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
      kernelModules = [ "dm-snapshot" "amdgpu" "radeon" ];
      enable = true;
      luks.devices = {
        luksroot = {
          device = "/dev/disk/by-uuid/4efa4377-ddcd-4ff3-97b8-637ee1425be8";
          preLVM = true;
        };
      };
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a9546c65-7276-4606-acb2-3e58cf089c70";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/F1F5-3861";
      fsType = "vfat";
    };

  swapDevices = [{
    device = "/dev/disk/by-uuid/c5d69b1f-32ab-4b8c-b82d-e895b804260d";
  }];

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      extraPackages = [
        pkgs.amdvlk
      ];
    };
  };

  # ==== BLUETOOTH ====
  hardware.bluetooth.enable = true;
}
